/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Decoder3 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    input [2:0] sel
);
    assign out_0 = (sel == 3'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 3'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 3'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 3'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 3'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 3'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 3'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 3'h7)? 1'b1 : 1'b0;
endmodule

module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Decoder2 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel
);
    assign out_0 = (sel == 2'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 2'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 2'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 2'h3)? 1'b1 : 1'b0;
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module ALU (
  input [3:0] INST,
  input A,
  input B,
  input C_In,
  output Out,
  output NOP,
  output C_Out,
  output C_En
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire [1:0] s4;
  wire Op_ADDSUB;
  wire Sig_ONOX;
  wire s5;
  wire Op_NAND;
  wire Op_OR;
  wire Op_XOR;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  assign s13 = ~ B;
  assign s15 = ~ C_In;
  assign s0 = INST[0];
  assign s1 = INST[1];
  assign s2 = INST[2];
  assign s3 = INST[3];
  assign s4 = INST[1:0];
  assign Op_ADDSUB = (s1 & ~ s2 & ~ s3);
  assign Sig_ONOX = (s2 & ~ s3);
  Decoder2 Decoder2_i0 (
    .sel( s4 ),
    .out_0( s5 ),
    .out_1( Op_NAND ),
    .out_2( Op_OR ),
    .out_3( Op_XOR )
  );
  assign s8 = (~ s2 & ~ s3 & ~ s1);
  assign s7 = (Sig_ONOX & s5);
  assign NOP = (~ s0 & s8);
  assign s14 = (s0 & Op_ADDSUB);
  Mux_2x1 Mux_2x1_i1 (
    .sel( s14 ),
    .in_0( B ),
    .in_1( s13 ),
    .out( s9 )
  );
  Mux_2x1 Mux_2x1_i2 (
    .sel( s14 ),
    .in_0( C_In ),
    .in_1( s15 ),
    .out( s11 )
  );
  assign C_En = (Op_ADDSUB | s7);
  assign s10 = (A ^ s9);
  assign s12 = ((s10 & s11) ^ (s9 & A));
  assign Out = ((~ (B & A) & (Sig_ONOX & Op_NAND)) | ((B | A) & (Sig_ONOX & Op_OR)) | ((s0 & s8) & A) | (Sig_ONOX & Op_XOR & (A ^ B)) | (Op_ADDSUB & (s11 ^ s10)) | s7);
  assign s16 = ~ s12;
  Mux_2x1 Mux_2x1_i3 (
    .sel( s14 ),
    .in_0( s12 ),
    .in_1( s16 ),
    .out( s6 )
  );
  assign C_Out = ((s6 & ~ s7) & Op_ADDSUB);
endmodule

module \GN14K5-norst  (
  input CLK,
  input D_I,
  input [3:0] INST,
  input SKP,
  output WE,
  output D_O,
  output R,
  output F,
  output IEN,
  output OEN,
  output CALL,
  output RET,
  output SKZ,
  output MEM
);
  wire OEN_temp;
  wire s0;
  wire s1;
  wire s2;
  wire IEN_temp;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire [3:0] s11;
  wire R_temp;
  wire F_temp;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire [3:0] s16;
  wire [2:0] s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire SKZ_temp;
  assign s3 = (IEN_temp & D_I);
  // Output_EN
  DIG_Register DIG_Register_i0 (
    .D( D_I ),
    .C( CLK ),
    .en( s4 ),
    .Q( OEN_temp )
  );
  // Input_EN
  DIG_Register DIG_Register_i1 (
    .D( D_I ),
    .C( CLK ),
    .en( s5 ),
    .Q( IEN_temp )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i2 (
    .sel( s20 ),
    .in_0( INST ),
    .in_1( 4'b0 ),
    .out( s16 )
  );
  assign s20 = (SKP | SKZ_temp);
  assign s11 = s16[3:0];
  assign s7 = s16[3];
  assign s17 = s16[2:0];
  Decoder3 Decoder3_i3 (
    .sel( s17 ),
    .out_0( s6 ),
    .out_1( s8 ),
    .out_2( s9 ),
    .out_3( s10 ),
    .out_4( s21 ),
    .out_5( s22 ),
    .out_6( s23 ),
    .out_7( s24 )
  );
  assign s1 = (s6 & s7);
  assign s2 = (s8 & s7);
  assign s5 = (s9 & s7);
  assign s4 = (s10 & s7);
  assign s25 = (s22 & s7);
  assign s26 = (s24 & s7);
  assign s27 = (s21 & s7);
  assign s0 = (OEN_temp & (s1 | s2));
  // CALL
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s27 ),
    .C( CLK ),
    .Q( CALL )
  );
  // RET
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s25 ),
    .C( CLK ),
    .Q( RET )
  );
  // MEM
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s26 ),
    .C( CLK ),
    .Q( MEM )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s0 ),
    .C( CLK ),
    .Q( WE )
  );
  ALU ALU_i8 (
    .INST( s11 ),
    .A( s3 ),
    .B( R_temp ),
    .C_In( F_temp ),
    .Out( s12 ),
    .NOP( s13 ),
    .C_Out( s14 ),
    .C_En( s15 )
  );
  assign s19 = ~ (s7 | s13);
  assign D_O = ((~ (s1 | s2) & R_temp) | (R_temp & s1) | (s18 & s2));
  assign s28 = (s18 & (s23 & s7));
  // Carry
  DIG_Register DIG_Register_i9 (
    .D( s14 ),
    .C( CLK ),
    .en( s15 ),
    .Q( F_temp )
  );
  // Result
  DIG_Register DIG_Register_i10 (
    .D( s12 ),
    .C( CLK ),
    .en( s19 ),
    .Q( R_temp )
  );
  // SKZ
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i11 (
    .D( s28 ),
    .C( CLK ),
    .Q( SKZ_temp )
  );
  assign s18 = ~ R_temp;
  assign R = R_temp;
  assign F = F_temp;
  assign IEN = IEN_temp;
  assign OEN = OEN_temp;
  assign SKZ = SKZ_temp;
endmodule
